# This file was generated by GoReleaser. DO NOT EDIT.
cask "lightfield" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "1f44cd93790b276d110c1c31b24996fdb65627db95ef5ad7b064cb0a159535bf"
      url "https://github.com/Lightfld/lightfield-cli/releases/download/v#{version}/lightfield_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "5aa795a0dd6f63c6d09602af7e753e512026058657b92d420a2159c73d0b9252"
      url "https://github.com/Lightfld/lightfield-cli/releases/download/v#{version}/lightfield_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "25b065014e33f61f563d6d52f2da67b715980f4a34bc4ca8c1f0f194abfea910"
      url "https://github.com/Lightfld/lightfield-cli/releases/download/v#{version}/lightfield_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b7ff1be574904a813feea40352bece59eb11477cd27f0c986184389f5ec00906"
      url "https://github.com/Lightfld/lightfield-cli/releases/download/v#{version}/lightfield_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lightfield"
  desc "The official CLI for Lightfield."
  homepage "https://lightfield.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lightfield"
  manpage "man/man1/lightfield.1.gz"
  bash_completion "completions/lightfield.bash"
  fish_completion "completions/lightfield.fish"
  zsh_completion "completions/lightfield.zsh"

  # No zap stanza required

end
