# This file was generated by GoReleaser. DO NOT EDIT.
cask "lightfield" do
  version "0.4.3"

  on_macos do
    on_intel do
      sha256 "a2c521efa843dbec1c8f2731cff6a54e513ef45c8ed2f09c2d96a7b7227ad307"
      url "https://github.com/Lightfld/lightfield-cli/releases/download/v#{version}/lightfield_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "101806de29e5ae773392cbaa8f4ce4e95f9a6185c2a0c925c8db3d771087be39"
      url "https://github.com/Lightfld/lightfield-cli/releases/download/v#{version}/lightfield_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "e1d878e70b0ef40ec8c515780b37d26680563f7263ca6bb39023e6eeedb6d631"
      url "https://github.com/Lightfld/lightfield-cli/releases/download/v#{version}/lightfield_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d1eeec919049db1d7a8b44d184665a9de988b41a3e3bb43bda44c9da4248f76b"
      url "https://github.com/Lightfld/lightfield-cli/releases/download/v#{version}/lightfield_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lightfield"
  desc "The official CLI for Lightfield."
  homepage "https://lightfield.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lightfield"
  manpage "man/man1/lightfield.1.gz"
  bash_completion "completions/lightfield.bash"
  fish_completion "completions/lightfield.fish"
  zsh_completion "completions/lightfield.zsh"

  # No zap stanza required

end
