# This file was generated by GoReleaser. DO NOT EDIT.
cask "lightfield" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "01baf4f93f3a20e6fff5695153ecc00441b5022d2940c1f9134c5ec3c6886d20"
      url "https://github.com/Lightfld/lightfield-cli/releases/download/v#{version}/lightfield_#{version}_macos_amd64.zip"
    end
    on_arm do
      sha256 "73e26dd07efc2913f3f630669f17d305e72304dbd1e13badeb9a1d5c37a8fe4a"
      url "https://github.com/Lightfld/lightfield-cli/releases/download/v#{version}/lightfield_#{version}_macos_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "f50b67945769ee1eb875f16efb59181ed79f68497dfe6da9584909bc789acda1"
      url "https://github.com/Lightfld/lightfield-cli/releases/download/v#{version}/lightfield_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d763fd97f6d9b471a6ab93da1a5d345770b8e75bff702d7f4ec74bde44719ec5"
      url "https://github.com/Lightfld/lightfield-cli/releases/download/v#{version}/lightfield_#{version}_linux_arm64.tar.gz"
    end
  end

  name "lightfield"
  desc "The official CLI for Lightfield."
  homepage "https://lightfield.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lightfield"
  manpage "man/man1/lightfield.1.gz"
  bash_completion "completions/lightfield.bash"
  fish_completion "completions/lightfield.fish"
  zsh_completion "completions/lightfield.zsh"

  # No zap stanza required

end
